import { writable, type Writable } from "svelte/store";
import type { DirectMessage, FriendRequest, NodeInfo, Post } from "./types";

export const myInfo: Writable<NodeInfo | null> = writable(null);
export const connectedPeers: Writable<string[]> = writable([]);
export const friendList: Writable<string[]> = writable([]);
export const pendingRequests: Writable<[string, FriendRequest][]> = writable([]);
export const postInput: Writable<string> = writable('');
export const addFriendAddress: Writable<string> = writable('');
export const addFriendMessage: Writable<string> = writable('');
export const relayAddress: Writable<string> = writable('');
export const isStarted: Writable<boolean> = writable(false);
export const showSendFriendRequestModal: Writable<boolean> = writable(false);
export const showFriendRequestsModal: Writable<boolean> = writable(false);
export const showRelaySettingsModal: Writable<boolean> = writable(false);
export const showProfileModal: Writable<boolean> = writable(false);
export const contextMenuVisible: Writable<boolean> = writable(false);
export const contextMenuLocation: Writable<[number, number]> = writable([0, 0]);
export const contextMenuPeer: Writable<string | null> = writable(null);
export const profilePeer: Writable<{ peerId: string, isFriend: boolean } | null> = writable(null);
export const nicknames: Writable<Map<string, string>> = writable(new Map<string, string>());
export const editingPeer: Writable<string | null> = writable(null);
export const draftNickname: Writable<string> = writable('');
export const directMessageOpen: Writable<boolean> = writable(false);
export const activeDMPeerId: Writable<string | null> = writable(null);
export const directMessages: Writable<DirectMessage[]> = writable([]);
export const directMessageInput: Writable<string> = writable('');
export const openBoardPeerId: Writable<string | null> = writable(null);
export const posts: Writable<Post[]> = writable([]);